[workspace]
members = [
    "crates/core", "crates/catchup-json", "crates/catchup-proto", "crates/server",
]
resolver = "2"

[workspace.package]
authors = ["odeg"]
description = "A pure rust app that enables anyone to create streams and post updates, which are viewed by the subscribers."
